name: Self-Hosted Runner Test

on:
  workflow_dispatch:

jobs:
  test-runner:
    name: Test HFA Runner
    runs-on: [self-hosted, Windows, X64]

    steps:

      - name: Show runner information
        shell: powershell
        run: |
          Write-Host "Computer: $env:COMPUTERNAME"
          Write-Host "User: $env:USERNAME"
          Write-Host "PowerShell: $($PSVersionTable.PSVersion)"

      - name: Verify SqlPackage
        shell: powershell
        run: |
          sqlpackage /Version

      - name: Verify SQL connectivity
        shell: powershell
        run: |
          sqlcmd `
            -S "hfa" `
            -d "HealthcareCICD" `
            -E `
            -Q "SELECT @@SERVERNAME AS ServerName, DB_NAME() AS DatabaseName;"